Traceback (most recent call last):
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_metadata_m = df_metadata[C == 'M']
df_metadata_f = df_metadata[df_metadata['mouse.sex'] == 'F']

print('\n Filtramos por sexo de rat√≥n y tenemos que: ')
print(f"üê≠ Machos: {df_metadata_m.shape[0]}")
print(f"üê≠ Hembras: {df_metadata_f.shape[0]}")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[16], line 1[0m
[1;32m----> 1[0m df_metadata_m [38;5;241m=[39m df_metadata[[43mC[49m [38;5;241m==[39m [38;5;124m'[39m[38;5;124mM[39m[38;5;124m'[39m]
[0;32m      2[0m df_metadata_f [38;5;241m=[39m df_metadata[df_metadata[[38;5;124m'[39m[38;5;124mmouse.sex[39m[38;5;124m'[39m] [38;5;241m==[39m [38;5;124m'[39m[38;5;124mF[39m[38;5;124m'[39m]
[0;32m      4[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m Filtramos por sexo de rat√≥n y tenemos que: [39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'C' is not defined

